### PR TITLE
Add usage videos (Fix #17)

### LINKED ISSUE #17: Usage videos
Add a few videos or animations to the README demonstrating usage of `get-mac` command and the Python module `getmac`. These can be recorded using [asciinema](https://asciinema.org/) or other such tools.

### LINKED ISSUE #21: Test functionality on Anaconda

### PR DESCRIPTION
**Pull request by fortunate-man**

### CODE REVIEW

**Comment by fortunate-man** [comment]
Hmm, looks like the videos are not previewing on the README page. Hold on, please.

**Comment by fortunate-man** [comment]
Seems to preview now! I've added two asciicasts.

**Comment by GhostofGoes** [comment]
A few things. For the first video, the `--version` flag is redundant, and I'd rather it show usage of at least a few of the other arguments that do matter (`-n` for hosts and `-i` for interfaces). Two commands you could run would be `get-mac -n 192.168.0.1` (replace IP with your Router's IP) and `get-mac -i eth0` (or another interface on your machine). 

Don't include the "exit" command in either video.

For the second video: Same as the first, show example of a remote host and a local interface.

**Comment by fortunate-man** [comment]
@GhostofGoes Sure, I'll do that! I'm slightly busy today with life, I'll be sure to make the new videos tomorrow.

**Comment by fortunate-man** [comment]
@GhostofGoes I've made the changes you've asked for. Although, the "exit" command in the recording seems to be a bug with asciinema (https://github.com/asciinema/asciinema/issues/265), and I could not remove it. I tried out some more tools like `ttystudio` and `showterm`, but none of them worked for me.

**Comment by GhostofGoes** [comment]
Oh, this is awesome! Thank you so much 😄

**Pull request merged**
